### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [dominic-meads/HDMI_FPGA#1]
Hello!

I found your project from https://github.com/yeokm1/graphics-gremlin-hdmi

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by dominic-meads** [comment]
Hi Alexey,

Thanks for the email! I'm glad people are using my code. Feel free to copy,
change, and use the code whatever way you want.

I am not super familiar with licensing on Github, but I just added a MIT
license, because that seemed the most simple and gave all users the most
permissions. HDMI_FPGA/License at master · dominic-meads/HDMI_FPGA
(github.com)
<https://github.com/dominic-meads/HDMI_FPGA/blob/master/License>

Let me know if this works for you and I hope your project turns out well :)

-Dominic

**Comment by vazhnov** [comment]
MIT license — amazing!
Thank you!
